In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]]
            )
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.shape

(3, 3)

In [4]:
arr.ndim

2

In [7]:
tensor_3d = np.array([
                        [[1,2], [3,4]],
                        [[5,6], [7,8]]
                     ]
                )

tensor_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
tensor_3d.shape

(2, 2, 2)

In [9]:
tensor_3d.ndim

3

In [13]:
tensor_3d[0][0][1]

2

In [15]:
arr[0][1]

2

## Common Operations

In [16]:
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

B = np.array([[1,0,3],
             [4,-1,6],
             [7,-2,9]])

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
A + B

array([[ 2,  2,  6],
       [ 8,  4, 12],
       [14,  6, 18]])

In [19]:
2 * A

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Matrix Multiplication

In [22]:
A @ B

array([[ 30,  -8,  42],
       [ 66, -17,  96],
       [102, -26, 150]])

In [23]:
A = np.array([[1,2],
             [3,4],
             [5,6]])

B = np.array([[2], [1]])

In [24]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
B

array([[2],
       [1]])

In [26]:
A @ B

array([[ 4],
       [10],
       [16]])

In [27]:
np.transpose(A @ B)

array([[ 4, 10, 16]])

In [28]:
at = np.transpose(A)

In [29]:
at

array([[1, 3, 5],
       [2, 4, 6]])

In [30]:
bt = np.transpose(B)

In [31]:
bt

array([[2, 1]])

In [33]:
bt @ at

array([[ 4, 10, 16]])