In [1]:
import numpy as np

In [2]:
a = np.array([3,4])

a

array([3, 4])

In [3]:
b = np.array([3,7.5,9,10])
b

array([ 3. ,  7.5,  9. , 10. ])

In [4]:
a.shape

(2,)

In [5]:
b.shape

(4,)

## Vector Addition

In [7]:
a = np.array([1,2])
b = np.array([0,3])

a + b

array([1, 5])

## Scalar Multiplication

In [8]:
2.5 * a

array([2.5, 5. ])

In [9]:
c = 2.5 * a
c

array([2.5, 5. ])