## Learning objectives:

* How numpy arrays are different from python lists
* How to perform basic math operations on numpy arrays

In [1]:
a = [1,2,3]
b = [4,5,6]

In [2]:
a + b

[1, 2, 3, 4, 5, 6]

In [3]:
a

[1, 2, 3]

In [4]:
b

[4, 5, 6]

In [5]:
c = a + b

In [6]:
c

[1, 2, 3, 4, 5, 6]

In [8]:
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [9]:
import numpy as np

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [11]:
arr1 + arr2

array([5, 7, 9])

In [12]:
arr1 * 2

array([2, 4, 6])

In [13]:
arr2 ** 2

array([16, 25, 36])

In [14]:
2 / arr1

array([2.        , 1.        , 0.66666667])

In [16]:
arr1 < arr2

array([ True,  True,  True])

## Arithmetic operations on 2D array

In [17]:
mat1 = np.array([[1,2,5], [6,7,0]])
mat1

array([[1, 2, 5],
       [6, 7, 0]])

In [18]:
mat2 = np.array([[3,4,1], [2,1,0]])
mat2

array([[3, 4, 1],
       [2, 1, 0]])

In [19]:
mat1 * mat2

array([[ 3,  8,  5],
       [12,  7,  0]])

## Matrix multiplication

In [21]:
smat1 = np.array([[1,2,5], [6,7,0], [2,3,4]])
smat2 = np.array([[3,4,1], [2,1,0], [1,1,1]])

In [22]:
smat1 @ smat2

array([[12, 11,  6],
       [32, 31,  6],
       [16, 15,  6]])

In [23]:
np.dot(smat1, smat2)

array([[12, 11,  6],
       [32, 31,  6],
       [16, 15,  6]])