## Learning Objectives:

* How broadcasting works
* How numpy performs arithmetic on arrays of different shape

In [1]:
import numpy as np

In [2]:
x = np.arange(5).reshape(1,5)
x

array([[0, 1, 2, 3, 4]])

In [3]:
x + 5

array([[5, 6, 7, 8, 9]])

In [4]:
x.shape

(1, 5)

In [6]:
y = np.arange(20).reshape(5,4)

y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
x + y

ValueError: operands could not be broadcast together with shapes (1,5) (5,4) 

## Broadcasting rule

> Two arrays are compatible for broadcasting if their corresponding axis lengths match or if either of the lengths is 1.

In [9]:
a = np.arange(48).reshape((6,1,8))
b = np.arange(32).reshape((1,4,8))

In [10]:
a


array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47]]])

In [11]:
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]])

In [13]:
c = a + b

In [14]:
c.shape

(6, 4, 8)

In [15]:
x

array([[0, 1, 2, 3, 4]])

In [16]:
x.shape

(1, 5)

In [17]:
z = np.arange(10).reshape(2,5)
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
x + z

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])