## Learning objectives:

* How to access elements from different types of arrays.
* How to slice or get a subset of a numpy array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 50, 5)

In [3]:
arr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [5]:
arr[3]

16

In [6]:
arr[3:]

array([16, 21, 26, 31, 36, 41, 46])

In [7]:
arr[3:7]

array([16, 21, 26, 31])

In [8]:
arr[3:7:2]

array([16, 26])

In [11]:
arr[::-1]

array([46, 41, 36, 31, 26, 21, 16, 11,  6,  1])

## Indexing and slicing 2D array

In [12]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr_2d[1][1]

5

In [14]:
arr_2d[1,1]

5

In [15]:
arr_2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [16]:
arr_2d[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [17]:
arr_2d[:, :-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

## 3D arrays

In [18]:
arr_3d = np.array([
    [
        [1,2,3], [4,5,6], [7,8,9]
    ],
    [
        [10, 11, 12], [13, 14, 15], [16, 17, 18]
    ]
])

arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
arr_3d.ndim


3

In [20]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr_3d[0,0]

array([1, 2, 3])

In [23]:
arr_3d[0, 0, 1]

2

In [24]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
arr_3d.shape

(2, 3, 3)

In [27]:
arr_3d[1, 1, 2]

15

In [31]:
arr_3d[1, 1, 2]

15

In [32]:
arr_3d[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

## Boolean Indexing

In [33]:
arr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [34]:
arr > 21

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
arr[arr > 21]

array([26, 31, 36, 41, 46])

In [36]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr_2d >= 5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [38]:
arr_2d[arr_2d >= 5]

array([5, 6, 7, 8, 9])

In [39]:
names = np.array(['Tom', 'Mak', 'Bill', 'Katey'])
names == "Katey"

array([False, False, False,  True])

In [40]:
names[names == "Katey"]

array(['Katey'], dtype='<U5')

## Operators

In [41]:
names[(names == "Katey") | (names == "Bill")]

array(['Bill', 'Katey'], dtype='<U5')

In [42]:
names[(names == "Katey") & (names == "Bill")]

array([], dtype='<U5')

In [43]:
arr_2d[(arr_2d > 3) & (arr_2d < 10)]

array([4, 5, 6, 7, 8, 9])

## Checking with two different arrays

In [44]:
names

array(['Tom', 'Mak', 'Bill', 'Katey'], dtype='<U5')

In [46]:
data = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
    
])

data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
names == "Bill"

array([False, False,  True, False])

In [48]:
data[:, names=="Bill"]

array([[ 3],
       [ 7],
       [11],
       [15]])