## Learning objectives:

* **How to create n-dimensional arrays using some placeholder functions:**
1. np.array()
2. np.zeros()
3. np.empty()
4. np.arange()
5. np.linspace()
* **How to convert the data type of a numpy array**

In [1]:
!pip install numpy

In [2]:
## import the package

import numpy as np

## Creating NumPy arrays using `np.array()`

In [3]:
price = [1200, 50, 12, 13.5, 200]

type(price)


list

In [4]:
price_arr = np.array(price)
price_arr

array([1200. ,   50. ,   12. ,   13.5,  200. ])

In [5]:
type(price_arr)

numpy.ndarray

In [6]:
price_arr.dtype

dtype('float64')

In [8]:
arr2 = np.array([2,3,4,5,6])
print(arr2)

[2 3 4 5 6]


In [9]:
arr3 = np.array([2,3,4,5,'tom'])
arr3

array(['2', '3', '4', '5', 'tom'], dtype='<U21')

In [10]:
arr3.dtype

dtype('<U21')

In [11]:
type(arr3)

numpy.ndarray

In [12]:
arr3.shape

(5,)

In [13]:
arr3.ndim

1

In [14]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr_2d.ndim

2

In [17]:
arr_2d.shape

(3, 3)

In [18]:
arr_2d.size

9

In [19]:
arr_3d = np.array([
    [[1,2], [3,4],
    [5,6], [7,8]]
]
)

In [20]:
arr_3d

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [21]:
arr_3d.ndim

3

In [22]:
arr_3d.shape

(1, 4, 2)

In [23]:
arr_3d[0]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [24]:
arr_3d = np.array([
    [[1,2], [3,4],
    [5,6], [7,8]],
    [[1,2], [3,4],
    [5,6], [7,8]]
]
)

In [25]:
arr_3d.shape

(2, 4, 2)

In [26]:
arr_3d.size

16

In [27]:
arr_3d[1]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
arr_3d[0]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
arr_3d[0][2].shape

(2,)

In [31]:
arr_3d[0][2][1]

6

In [32]:
arr_3d.shape

(2, 4, 2)

## np.zeros

In [34]:
arr_1d = np.zeros(10)

In [35]:
arr_1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
arr2_0 = np.zeros((5,5))
arr2_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## np.empty()

In [38]:
arr2_empty = np.empty((2,3))
arr2_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.arange()

In [39]:
range(1, 10, 1)

range(1, 10)

In [40]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [45]:
odd_num = np.arange(1, 100, 2)

In [46]:
odd_num

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## np.linspace()

In [47]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [51]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## How to work with data types

In [52]:
odd_num = np.arange(1, 100, 2, dtype=np.float64)
print(odd_num)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49. 51. 53. 55. 57. 59. 61. 63. 65. 67. 69. 71.
 73. 75. 77. 79. 81. 83. 85. 87. 89. 91. 93. 95. 97. 99.]


In [55]:
narr = np.array([1, 2.5, 3], dtype=np.int32)

In [56]:
narr

array([1, 2, 3], dtype=int32)

In [57]:
a = np.array([2,4,5.6, 6, 7])
a.dtype

dtype('float64')

In [58]:
a_int = a.astype(np.int32)
a_int

array([2, 4, 5, 6, 7], dtype=int32)