## Learning Objectives:

* Generating random numbers using `np.random` module.
* Generating random normally distributed data.
* How to generate the same set of numbers everytime using seed.
* Other functions you can use.

In [1]:
import numpy as np

In [2]:
normal_data = np.random.normal(size=(5,3))
normal_data

array([[ 0.64579048,  0.03257397,  0.59808065],
       [ 0.70817173,  0.5781209 ,  0.14540588],
       [-0.51033706, -0.64039698,  1.12909601],
       [-0.17433335,  0.0944369 , -1.39771109],
       [ 0.68876983,  0.44019564,  1.1440783 ]])

## Compare the speed with python's builtin random module

In [3]:
from random import normalvariate

n = 10000
%timeit [normalvariate(0,1) for _ in range(n)]

5.67 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit np.random.normal(size=n)

211 µs ± 6.71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Using seed()

In [7]:
np.random.randint(1, 10, size=(10))

array([9, 1, 6, 1, 9, 7, 2, 4, 3, 8])

In [10]:
np.random.seed(5)
np.random.randint(1, 10, size=(10))

array([4, 7, 7, 1, 9, 5, 8, 1, 1, 8])

## Other important random generation functions

In [12]:
perm1 = np.random.permutation(15)

perm1

array([14, 11, 12,  3, 13,  6,  4,  8, 10,  5,  0,  7,  2,  1,  9])

In [15]:
arr = [5,6,2,1,0]
np.random.shuffle(arr)

In [16]:
arr

[2, 1, 6, 5, 0]

In [17]:
np.random.binomial(1, 0.5, size=(10))

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1])

In [18]:
np.random.uniform(size=(10))

array([0.5797214 , 0.0645069 , 0.17724613, 0.34152709, 0.60870258,
       0.19547496, 0.12154847, 0.93467951, 0.31097992, 0.47431657])