## Learning Objectives:

* Reshaping arrays using `reshape()`

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,50,5)
arr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [3]:
print(arr.shape)

(10,)


In [4]:
arr = arr.reshape(5,2)
arr

array([[ 1,  6],
       [11, 16],
       [21, 26],
       [31, 36],
       [41, 46]])

In [5]:
arr.shape

(5, 2)

In [7]:
arr2 = np.arange(20).reshape(4,5, order="C")
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
arr3 = np.arange(20).reshape(4,5, order="F")
arr3

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [9]:
arr_3d = np.arange(20).reshape((4,5,1), order="C")
arr_3d

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [10]:
arr_3d.shape

(4, 5, 1)

In [11]:
arr = np.arange(20).reshape(2,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [12]:
arr.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [13]:
arr.shape

(2, 10)

In [16]:
arr = arr.reshape(-1, 5)

In [17]:
arr.shape

(4, 5)

## Transposing an array

In [18]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
arr.shape

(4, 5)

In [21]:
arr = arr.transpose()

In [22]:
arr.shape

(5, 4)

In [23]:
arr.T

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Flattening an array

In [25]:
arr = arr.flatten()

In [26]:
arr.shape

(20,)