## Learning Objectives:

* Stacking arrays - `np.concatenate()`, `np.vstack()`, `np.hstack()`
* Splitting arrays - `np.split()`

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[7,8,9],
                 [10, 11, 12]])

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [3]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [5]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [7]:
arr3 = np.arange(20).reshape(4,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
np.vstack((arr1, arr3))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

## Splitting

In [9]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
arr1, arr2, arr3, arr4 = np.split(arr, 4)

In [12]:
arr1

array([[0, 1, 2]])

In [13]:
arr2

array([[3, 4, 5]])

In [14]:
arr1, arr2, arr3 = np.split(arr, [1, 3])
print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"arr3: {arr3}")

arr1: [[0 1 2]]
arr2: [[3 4 5]
 [6 7 8]]
arr3: [[ 9 10 11]]
