## Learning Objectives:

* Exploring commonly used universal mathematical and statistical functions.
* Unary and binary functions
* Making a non-vectorized function vectorized

In [10]:
import numpy as np

In [11]:
x = np.arange(1, 100, 10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [12]:
sq = np.square(x)
sq

array([   1,  121,  441,  961, 1681, 2601, 3721, 5041, 6561, 8281])

In [13]:
exp = np.exp(x)
exp

array([2.71828183e+00, 5.98741417e+04, 1.31881573e+09, 2.90488497e+13,
       6.39843494e+17, 1.40934908e+22, 3.10429794e+26, 6.83767123e+30,
       1.50609731e+35, 3.31740010e+39])

In [14]:
np.sin(x)

array([ 0.84147098, -0.99999021,  0.83665564, -0.40403765, -0.15862267,
        0.67022918, -0.96611777,  0.95105465, -0.62988799,  0.10598751])

In [15]:
y = np.linspace(1, 10, 20)
y

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [16]:
np.ceil(y)

array([ 1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,  7.,
        8.,  8.,  9.,  9., 10., 10., 10.])

In [17]:
np.floor(y)

array([ 1.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,
        7.,  7.,  8.,  8.,  9.,  9., 10.])

## Binary universal functions

In [18]:
sub1_scores = np.random.randint(20, 100, size=(10))
sub2_scores = np.random.randint(20, 100, size=(10))

In [19]:
print(sub1_scores)
print(sub2_scores)

[77 49 98 88 95 76 81 20 74 85]
[71 95 27 85 40 44 32 36 83 94]


In [20]:
total_score = np.add(sub1_scores, sub2_scores)
total_score

array([148, 144, 125, 173, 135, 120, 113,  56, 157, 179])

In [21]:
best_score_out_of_two = np.maximum(sub1_scores, sub2_scores)

In [22]:
best_score_out_of_two

array([77, 95, 98, 88, 95, 76, 81, 36, 83, 94])

In [23]:
base_arr = np.arange(1, 10)
power_arr = np.arange(1, 10)
ans = np.power(base_arr, power_arr)
ans

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489])

## Making a non-vectorized function vectorized

In [24]:
from math import factorial

In [25]:
a = 5
factorial(a)

120

In [26]:
x = np.arange(1, 6)
factorial(x)

TypeError: only integer scalar arrays can be converted to a scalar index

In [27]:
vec_fact = np.vectorize(factorial)


In [28]:
print(x)
print(vec_fact(x))

[1 2 3 4 5]
[  1   2   6  24 120]
