## Learning Objectives:

* Introduction to pandas special data structures - series
* How to define series
* Working with series along with NumPy .

In [17]:
import numpy as np
import pandas as pd

## Creating series

In [2]:
ser1 = pd.Series([2,3,4,5,6])
ser1

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [3]:
type(ser1)

pandas.core.series.Series

In [4]:
ser1.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
ser1.values

array([2, 3, 4, 5, 6])

In [6]:
type(ser1.values)

numpy.ndarray

In [7]:
##creating a series with index

scores = pd.Series([100, 200, 300, 400, 500],
                  index=['s1', 's2', 's3', 's4', 's5'])


In [8]:
scores

s1    100
s2    200
s3    300
s4    400
s5    500
dtype: int64

In [9]:
scores.index

Index(['s1', 's2', 's3', 's4', 's5'], dtype='object')

In [10]:
scores.values

array([100, 200, 300, 400, 500])

In [11]:
scores[1]

200

In [12]:
scores['s2']

200

In [13]:
scores > 250

s1    False
s2    False
s3     True
s4     True
s5     True
dtype: bool

In [14]:
scores[scores > 250]

s3    300
s4    400
s5    500
dtype: int64

In [15]:
## perform arithmetic operations
(scores * 5)/100


s1     5.0
s2    10.0
s3    15.0
s4    20.0
s5    25.0
dtype: float64

In [18]:
np.sin(scores)

s1   -0.506366
s2   -0.873297
s3   -0.999756
s4   -0.850919
s5   -0.467772
dtype: float64

In [19]:
np.log(scores)

s1    4.605170
s2    5.298317
s3    5.703782
s4    5.991465
s5    6.214608
dtype: float64

In [20]:
scores

s1    100
s2    200
s3    300
s4    400
s5    500
dtype: int64

In [21]:
scores['s3'] = 150
scores

s1    100
s2    200
s3    150
s4    400
s5    500
dtype: int64

In [23]:
's3' in scores

True

In [24]:
inventory = {'laptop': 1500, 'bag': 50, 'TV': 300, 'speakers': 400}
inventory

{'laptop': 1500, 'bag': 50, 'TV': 300, 'speakers': 400}

In [25]:
inventory_ser = pd.Series(inventory)
inventory_ser

laptop      1500
bag           50
TV           300
speakers     400
dtype: int64

In [26]:
inventory_ser.values

array([1500,   50,  300,  400])

In [27]:
inventory_ser['keyboard'] = None
inventory_ser

laptop      1500
bag           50
TV           300
speakers     400
keyboard    None
dtype: object

In [28]:
inventory_ser.isnull()

laptop      False
bag         False
TV          False
speakers    False
keyboard     True
dtype: bool

In [29]:
inventory_ser[inventory_ser.isnull()]

keyboard    None
dtype: object